#!/usr/bin/with-contenv bashio
# ==============================================================================
# Optolink Splitter add-on launcher
#
# - Generates settings_ini.py from the add-on options (auto-detects the
#   Mosquitto broker add-on via the Supervisor MQTT service if no broker
#   is configured).
# - Seeds /config (= /addon_configs/<slug>/ on the host) with a Vitocal /
#   Vitotronic 200 WO1C poll list template on first start.
# - Publishes Home Assistant MQTT discovery messages (homeassistant_publish.py)
#   when a homeassistant_poll_list.py is in use.
# - Starts optolinkvs2_switch.py.
#
# Power-user escape hatch: if you place your own settings_ini.py into
# /addon_configs/<slug>/ it takes precedence over the generated one.
# ==============================================================================
set -e

SPLITTER_DIR="/opt/optolink-splitter"
GEN_DIR="/data/gen"
CONF_DIR="/config"

mkdir -p "${GEN_DIR}"

# ------------------------------------------------------------------------------
# Read options
# ------------------------------------------------------------------------------
OPTOLINK_PORT="$(bashio::config 'optolink_port')"
VITOCONNECT_PORT="$(bashio::config 'vitoconnect_port')"
MQTT_TOPIC="$(bashio::config 'mqtt_topic')"
POLL_INTERVAL="$(bashio::config 'poll_interval')"
WO1C_ENERGY="$(bashio::config 'wo1c_energy')"
TCPIP_PORT="$(bashio::config 'tcpip_port')"
LOG_LEVEL_STR="$(bashio::config 'log_level')"

# booleans -> Python literals
MQTT_RETAIN="False";      bashio::config.true 'mqtt_retain'       && MQTT_RETAIN="True"
SHOW_OPTO_RX="False";     bashio::config.true 'debug_optolink_rx' && SHOW_OPTO_RX="True"
NO_LOGGER_FILE="True";    bashio::config.true 'write_log_file'    && NO_LOGGER_FILE="False"

# log level name -> numeric
case "${LOG_LEVEL_STR}" in
    debug)   LOG_LEVEL=10 ;;
    warning) LOG_LEVEL=30 ;;
    error)   LOG_LEVEL=40 ;;
    *)       LOG_LEVEL=20 ;;
esac

# ------------------------------------------------------------------------------
# MQTT broker: explicit option, else Supervisor-provided service (Mosquitto)
# ------------------------------------------------------------------------------
MQTT_HOST=""
MQTT_PORT="1883"
MQTT_USERNAME="$(bashio::config 'mqtt_user')"
MQTT_PASSWORD="$(bashio::config 'mqtt_password')"

if bashio::config.has_value 'mqtt_broker'; then
    BROKER="$(bashio::config 'mqtt_broker')"
    MQTT_HOST="${BROKER%%:*}"
    if [[ "${BROKER}" == *:* ]]; then
        MQTT_PORT="${BROKER##*:}"
    fi
elif bashio::services.available "mqtt"; then
    MQTT_HOST="$(bashio::services 'mqtt' 'host')"
    MQTT_PORT="$(bashio::services 'mqtt' 'port')"
    if ! bashio::var.has_value "${MQTT_USERNAME}"; then
        MQTT_USERNAME="$(bashio::services 'mqtt' 'username')"
        MQTT_PASSWORD="$(bashio::services 'mqtt' 'password')"
    fi
    bashio::log.info "Using Supervisor MQTT service: ${MQTT_HOST}:${MQTT_PORT}"
else
    bashio::log.warning "No MQTT broker configured and no MQTT service found."
    bashio::log.warning "Install the Mosquitto broker add-on, or set the 'mqtt_broker' option."
fi

if bashio::var.has_value "${MQTT_HOST}"; then
    MQTT_BROKER_PY="\"${MQTT_HOST}:${MQTT_PORT}\""
else
    MQTT_BROKER_PY="None"
fi

if bashio::var.has_value "${MQTT_USERNAME}"; then
    MQTT_USER_PY="\"${MQTT_USERNAME}:${MQTT_PASSWORD}\""
else
    MQTT_USER_PY="None"
fi

if bashio::var.has_value "${VITOCONNECT_PORT}"; then
    VITOCONNECT_PY="'${VITOCONNECT_PORT}'"
else
    VITOCONNECT_PY="None"
fi

if [[ "${TCPIP_PORT}" -gt 0 ]]; then
    TCPIP_PY="${TCPIP_PORT}"
else
    TCPIP_PY="None"
fi

# ------------------------------------------------------------------------------
# Generate settings_ini.py
# ------------------------------------------------------------------------------
SETTINGS_FILE="${GEN_DIR}/settings_ini.py"

cat > "${SETTINGS_FILE}" <<EOF
# Generated by the Optolink Splitter add-on from its options - DO NOT EDIT.
# (Edit the add-on configuration instead. To fully override, place your own
#  settings_ini.py into the add-on config folder /addon_configs/<slug>/.)

# Serial ports
port_optolink = '${OPTOLINK_PORT}'
port_vitoconnect = ${VITOCONNECT_PY}
vs2timeout = 120
vs1protocol = False     # Vitotronic 200 WO1C talks VS2/P300

# MQTT
mqtt_broker = ${MQTT_BROKER_PY}
mqtt_user = ${MQTT_USER_PY}
mqtt_tls_enable = False
mqtt_tls_skip_verify = False
mqtt_tls_ca_certs = None
mqtt_tls_certfile = None
mqtt_tls_keyfile = None
mqtt_logging = False

# MQTT topics
mqtt_topic = "${MQTT_TOPIC}"
mqtt_listen = "${MQTT_TOPIC}/cmnd"
mqtt_respond = "${MQTT_TOPIC}/resp"
mqtt_fstr = "{dpname}"
mqtt_retain = ${MQTT_RETAIN}
mqtt_no_redundant = False

# TCP/IP (Viessdata etc.)
tcpip_port = ${TCPIP_PY}

# Optolink communication timing
fullraw_eot_time = 0.05
fullraw_timeout = 2
olbreath = 0.05

# Logging
show_opto_rx = ${SHOW_OPTO_RX}
log_optolink = False
log_vitoconnect = False
viconn_to_mqtt = True
no_logger_file = ${NO_LOGGER_FILE}
log_level = ${LOG_LEVEL}

# Data formatting
max_decimals = 4
data_hex_format = '02x'
resp_addr_format = 'x'
retcode_format = 'd'

# Viessdata CSV (disabled in the add-on)
write_viessdata_csv = False
viessdata_csv_path = ""
buffer_to_write = 60
dec_separator = ","

# Resilience
max_restarts = 5
restart_delay = 10
max_vicon_tries = 3
max_comm_errors = 10
retry_counters_reset = 30
readback_delay_set = 1

# Polling (a poll_interval inside your poll list file takes precedence)
poll_interval = ${POLL_INTERVAL}

# WO1C daily/weekly energy statistics (0 = disabled, N = every N-th cycle)
wo1c_energy = ${WO1C_ENERGY}

# 1-Wire sensors (add via custom_settings option or your own settings_ini.py)
w1sensors = {}
EOF

# Append raw custom settings lines, if any
if bashio::config.has_value 'custom_settings'; then
    {
        echo ""
        echo "# --- custom_settings from add-on options ---"
        while read -r line; do
            echo "${line}"
        done <<< "$(bashio::config 'custom_settings')"
    } >> "${SETTINGS_FILE}"
fi

# ------------------------------------------------------------------------------
# Seed the add-on config folder on first start
# ------------------------------------------------------------------------------
if [[ ! -f "${CONF_DIR}/poll_list.py" && ! -f "${CONF_DIR}/homeassistant_poll_list.py" ]]; then
    bashio::log.info "No poll list found - installing Vitocal WO1C starter template."
    cp /opt/templates/homeassistant_poll_list.py "${CONF_DIR}/homeassistant_poll_list.py"
fi
# reference material (never auto-loaded due to .example suffix)
cp -f "${SPLITTER_DIR}/poll_list.py.example" "${CONF_DIR}/poll_list.py.example" || true
cp -f "${SPLITTER_DIR}/homeassistant_poll_list.py.example" "${CONF_DIR}/homeassistant_poll_list.py.upstream-example" || true

if [[ -f "${CONF_DIR}/settings_ini.py" ]]; then
    bashio::log.warning "Custom settings_ini.py found in the add-on config folder - it OVERRIDES the add-on options!"
fi

# ------------------------------------------------------------------------------
# Launch
# ------------------------------------------------------------------------------
# /config first so user files win; then generated settings; then the splitter code.
export PYTHONPATH="${CONF_DIR}:${GEN_DIR}:${SPLITTER_DIR}"
export PYTHONUNBUFFERED=1
cd "${CONF_DIR}"

# homeassistant_publish.py requires the splitter's LWT to be 'online', so it
# must run AFTER the splitter is up - do it in the background with retries.
if bashio::config.true 'ha_discovery' \
   && [[ -f "${CONF_DIR}/homeassistant_poll_list.py" ]] \
   && [[ ! -f "${CONF_DIR}/poll_list.py" ]]; then
    (
        for attempt in 1 2 3; do
            sleep 15
            bashio::log.info "Publishing HA MQTT discovery entities (attempt ${attempt}/3)..."
            if python3 "${SPLITTER_DIR}/homeassistant_publish.py"; then
                bashio::log.info "HA discovery entities published."
                exit 0
            fi
        done
        bashio::log.warning "HA discovery publish failed - is the splitter online (check LWT)?"
    ) &
fi

bashio::log.info "Starting Optolink Splitter on ${OPTOLINK_PORT} ..."
exec python3 "${SPLITTER_DIR}/optolinkvs2_switch.py"
